# Generated by Django 5.0.4 on 2024-04-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_post_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='product_pos_publish_5af627_idx',
            old_name='Product_pos_publish_984961_idx',
        ),
    ]
